# Application Name
spring.application.name=CineLingo

# MongoDB Connection
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=cinelingo

# Server Port
server.port=8081

# Logging
logging.level.org.springframework.data.mongodb=DEBUG

# File Upload Size (for audio/video files)
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

# Jackson (for JSON date formatting)
spring.jackson.serialization.write-dates-as-timestamps=false